spring:
  application:
    name: springboot-init
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
     store-type: redis
     timeout: 2592000 # 30 天过期
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://23.224.98.132:3306/xingchenBi?useSSL=false
    username: root
    password: 419520
  # Redis 配置
  redis:
    database: 1
    host: 23.224.98.132
    port: 6379
    timeout: 5000
    password: 419520
  # Elasticsearch 配置
  elasticsearch:
    uris: http://23.224.98.132:9200
    username: root
    password: 419520
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
#  对象存储
cos:
  client:
    accessKey: AKIDWrvkIYXGjwsXw83h5C1Zrsc4HDsGNEp8
    secretKey: 3qMbZGgphIdhU0FDuJSKuDF1WkgLksjJ
    region: ap-shanghai
    bucket: linxun-1310915694
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xingchen
    aesKey: qrtyguCCAAValMqOWmvou5pvMKH9ZERklLfit2z6fUe
    appId: wx5de2adad299dbb8a
    secret: 9651c497c0b8978f667c72c0cc3f3e19
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 23.224.98.132
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 鱼聪明 AI 配置（https://yucongming.com/）
yuapi:
  client:
    access-key: e0ti6v4ofmfxzu6lel1sgt456tntsyo6
    secret-key: b4dt5csxfoxzc6ccctu1bxkuik9i1yd0

